<a href="https://colab.research.google.com/github/gowrilvinod/GenAI-Content-Creation/blob/main/gemma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -U keras-nlp
!pip install -U keras

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.5/570.5 kB 3.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 950.8/950.8 kB 19.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 55.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.8/589.8 MB 1.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 54.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 59.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 44.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 62.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 36.8 MB/s eta 0:00:00
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.2.0
    Uninstalling ml-dtypes-0.2.0:
      Successfully uninstalled ml-dtypes-0.2.0
  Attempting uninstall: h5py
    Found existing installation: h5py 3.9.0
    Uninstalling h5py-3.9.0:
      Suc

In [2]:
import keras
import keras_nlp
import numpy as np

In [4]:
!pip install kaggle


In [5]:
from google.colab import files
files.upload()


Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"lgowrivinod","key":"1d8578547d771b0857b6c23878cd00b5"}'}

In [6]:
import shutil
shutil.move("kaggle.json", "/root/.kaggle/kaggle.json")


'/root/.kaggle/kaggle.json'

In [7]:
!chmod 600 /root/.kaggle/kaggle.json


In [8]:
from kaggle.api.kaggle_api_extended import KaggleApi
api = KaggleApi()
api.authenticate()


In [8]:
gemma_2b = keras_nlp.models.GemmaCausalLM.from_preset("gemma_2b_en")

100%|██████████| 143/143 [00:00<00:00, 236kB/s]


100%|██████████| 555/555 [00:00<00:00, 909kB/s]


100%|██████████| 4.67G/4.67G [01:17<00:00, 64.3MB/s]


100%|██████████| 401/401 [00:00<00:00, 552kB/s]


100%|██████████| 4.04M/4.04M [00:00<00:00, 16.0MB/s]


In [1]:
my_prompt = ['Please introduce me to you.']
gemma_2b.generate(my_prompt, max_length=360)

NameError: name 'gemma_2b' is not defined

In [14]:
from keras_nlp.models import GemmaTokenizer
# Load a preset tokenizer.
tokenizer = GemmaTokenizer.from_preset("gemma_2b_en")

# Tokenize some input.
display(tokenizer("Hello Kaggle!"))

# Detokenize some input.
display(tokenizer.detokenize([4521, 80600, 2315, 235341]))

Attaching 'metadata.json' from model 'keras/gemma/keras/gemma_2b_en/2' to your Colab notebook...
Attaching 'metadata.json' from model 'keras/gemma/keras/gemma_2b_en/2' to your Colab notebook...
Attaching 'tokenizer.json' from model 'keras/gemma/keras/gemma_2b_en/2' to your Colab notebook...
Attaching 'tokenizer.json' from model 'keras/gemma/keras/gemma_2b_en/2' to your Colab notebook...
Attaching 'assets/tokenizer/vocabulary.spm' from model 'keras/gemma/keras/gemma_2b_en/2' to your Colab notebook...


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([  4521,  80600,   2315, 235341], dtype=int32)>

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello Kaggle!'>

In [15]:
display(tokenizer(['Hello Kaggle!', "Nice to meet you"]))

<tf.RaggedTensor [[4521, 80600, 2315, 235341],
 [7731, 577, 4664, 692]]>

In [16]:
display(tokenizer.detokenize([
    [4521, 80600, 2315, 235341],
    [7731, 577, 4664, 692],
]))

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'Hello Kaggle!', b'Nice to meet you'], dtype=object)>

In [17]:
class LangChain:
    def __init__(self, system_prompt):
        self.system_prompt = system_prompt
        self.ai_prompt = "AI Prompt: "
        self.human_prompt = "Human Prompt: "
        self.conversation_log = []
        self.model = keras_nlp.models.GemmaCausalLM.from_preset("gemma_2b_en")
        self.tokenizer = keras_nlp.models.GemmaTokenizer.from_preset("gemma_2b_en")

In [20]:
    def add_human_message(self, message):
        self.conversation_log.append(self.human_prompt + message)

    def add_ai_message(self, message):
        self.conversation_log.append(self.ai_prompt + message)

    def generate_response(self, max_length=360):
        prompt = self.system_prompt + "\n" + "\n".join(self.conversation_log)
        tokenized_prompt = self.tokenizer(prompt).numpy()
        tokenized_prompt = tokenized_prompt[np.newaxis, :]  # Add batch dimension
        generated_tokens = self.model.generate(tokenized_prompt, max_length=max_length)[0]
        response = self.tokenizer.detokenize(generated_tokens).numpy().decode('utf-8')
        ai_response = response[len(prompt):].strip()  # Extract only the AI's response
        return ai_response

In [21]:
# Create an instance with an initial system prompt
system_prompt = "You are a helpful AI assistant."
lang_chain = LangChain(system_prompt)

# Add a human message
human_message = "Hello, how are you?"
lang_chain.add_human_message(human_message)

# Generate AI response
ai_response = lang_chain.generate_response()
lang_chain.add_ai_message(ai_response)

# Print the conversation
for message in lang_chain.conversation_log:
    print(message)

Attaching 'metadata.json' from model 'keras/gemma/keras/gemma_2b_en/2' to your Colab notebook...
Attaching 'metadata.json' from model 'keras/gemma/keras/gemma_2b_en/2' to your Colab notebook...
Attaching 'task.json' from model 'keras/gemma/keras/gemma_2b_en/2' to your Colab notebook...
Attaching 'config.json' from model 'keras/gemma/keras/gemma_2b_en/2' to your Colab notebook...
Attaching 'metadata.json' from model 'keras/gemma/keras/gemma_2b_en/2' to your Colab notebook...
Attaching 'metadata.json' from model 'keras/gemma/keras/gemma_2b_en/2' to your Colab notebook...
Attaching 'config.json' from model 'keras/gemma/keras/gemma_2b_en/2' to your Colab notebook...
Attaching 'config.json' from model 'keras/gemma/keras/gemma_2b_en/2' to your Colab notebook...


ResourceExhaustedError: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:Mul] name: 